# Generated by Django 5.0 on 2024-04-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('duracion', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.SmallIntegerField(default=5)),
                ('profesor', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ULULU',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('duracion', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=13)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=30)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=30)),
                ('fechaNacimiento', models.DateField(default='2000-01-01')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TernaApp.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMatricula', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TernaApp.materia')),
            ],
        ),
    ]
