# Generated by Django 5.0 on 2024-05-23 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('duracion', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.CharField(max_length=8, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=13)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=30)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=30)),
                ('fechaNacimiento', models.DateField(default='2000-01-01')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TernaApp.carrera')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_corte', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('segundo_corte', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('tercer_corte', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('nota_definitiva', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TernaApp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.SmallIntegerField(default=5)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TernaApp.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=13)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('fechaNacimiento', models.DateField(default='2000-01-01')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
