# Generated by Django 5.0 on 2024-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TernaApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretario",
            name="cedula",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
