# Generated by Django 5.0 on 2024-04-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ULULU',
        ),
    ]
