# Generated by Django 5.0 on 2024-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='id',
        ),
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cedula',
            field=models.CharField(default='1000000', max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fechaNacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='cedula',
            field=models.CharField(default=1000000, max_length=9, unique=True),
        ),
    ]
