# Generated by Django 5.0 on 2024-05-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0002_remove_profesor_id_profesor_apellido_profesor_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='seccion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materia',
            name='limite_estudiantes',
            field=models.SmallIntegerField(default=41),
        ),
        migrations.AddField(
            model_name='profesor',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
