# Generated by Django 5.0 on 2024-05-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0002_estudiante_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='publicaciones',
        ),
    ]
