# Generated by Django 5.0 on 2024-05-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TernaApp", "0002_alter_secretario_cedula"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secretario",
            old_name="apellido",
            new_name="apellidoPaterno",
        ),
    ]
