# Generated by Django 5.0 on 2024-04-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0002_delete_ululu'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
