# Generated by Django 5.0 on 2024-05-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TernaApp", "0003_rename_apellido_secretario_apellidopaterno"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primer_corte",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "segundo_corte",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "tercer_corte",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "nota_definitiva",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=4),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TernaApp.estudiante",
                    ),
                ),
            ],
        ),
    ]
