# Generated by Django 5.0 on 2024-04-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0003_carrera_materia_estudiante_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
