# Generated by Django 5.0 on 2024-04-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0003_estudiante_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
