# Generated by Django 5.0 on 2024-05-16 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0003_delete_imagen_delete_publicaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretario',
            old_name='apellidoMaterno',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='secretario',
            name='apellidoPaterno',
        ),
        migrations.AddField(
            model_name='secretario',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
