# Generated by Django 5.0 on 2024-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TernaApp", "0004_notaestudiante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="cedula",
            field=models.IntegerField(
                max_length=8, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
