# Generated by Django 5.0 on 2024-04-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0004_imagen_alter_estudiante_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_publicaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TernaApp.publicaciones'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='publicaciones',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='TernaApp.publicaciones'),
        ),
    ]
