# Generated by Django 5.0 on 2024-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TernaApp", "0005_alter_estudiante_cedula_alter_estudiante_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="cedula",
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="email",
            field=models.CharField(
                blank=True, max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
