# Generated by Django 5.0 on 2024-05-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0005_materia_limitantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
