# Generated by Django 5.0 on 2024-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TernaApp", "0006_alter_estudiante_cedula_alter_estudiante_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="cedula",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
