# Generated by Django 5.0 on 2024-04-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0006_alter_estudiante_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidoMaterno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidoPaterno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(max_length=60),
        ),
    ]
