# Generated by Django 5.0 on 2024-04-03 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0007_remove_estudiante_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TernaApp.carrera'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
