# Generated by Django 5.0 on 2024-04-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0008_rename_nombres_estudiante_nombre_estudiante_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
