# Generated by Django 5.0 on 2024-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0008_rename_nombres_estudiante_nombre_estudiante_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=13)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('materia', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=1)),
            ],
        ),
    ]
