# Generated by Django 5.0 on 2024-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0008_rename_nombres_estudiante_nombre_estudiante_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('R', 'Maquina')], default='F', max_length=1),
        ),
    ]
