# Generated by Django 5.0 on 2024-04-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TernaApp', '0009_alter_estudiante_nombre'),
        ('TernaApp', '0009_profesor'),
    ]

    operations = [
    ]
